window.SLIDES = [
  { n: 1,  label: 'Title' },
  { n: 2,  label: 'Self Intro' },
  { n: 3,  label: 'Homework' },
  { n: 4,  label: 'Two Angles' },
  { n: 5,  label: 'Core Message' },
  { n: 6,  label: 'Timeline' },
  { n: 7,  label: 'Profile' },
  { n: 8,  label: 'Stack Size' },
  { n: 9,  label: 'Ch.1 Cover' },
  { n: 10, label: 'Term Mapping' },
  { n: 11, label: 'Three Layers' },
  { n: 12, label: 'Case LG' },
  { n: 13, label: 'Ch.2 Cover' },
  { n: 14, label: 'Architecture' },
  { n: 15, label: 'Actual Stack' },
  { n: 16, label: 'Flow 3 Steps' },
  { n: 17, label: 'Case Studies' },
  { n: 18, label: 'Ch.3 Cover' },
  { n: 19, label: 'Split x Devices' },
  { n: 20, label: 'Philosophies' },
  { n: 21, label: 'Fossil Errors' },
  { n: 22, label: 'Ch.4 Cover' },
  { n: 23, label: 'Role Split' },
  { n: 24, label: 'Two Apps a Day' },
  { n: 25, label: 'Demo 1 Teaser' },
  { n: 26, label: 'Demo 2 Teaser' },
  { n: 27, label: 'Demo 3 Meta' },
  { n: 28, label: 'Closing' },
  { n: 29, label: 'Take Away' }
];
